package io.github.heyhey123.xiaojieorm.impl.pg.database

import io.github.heyhey123.xiaojieorm.impl.jdbc.database.JdbcDialect
import io.github.heyhey123.xiaojieorm.impl.jdbc.database.JdbcPageParameter
import io.github.heyhey123.xiaojieorm.impl.jdbc.database.JdbcPageSql

/** PostgreSQL-specific SQL rendering; query execution remains in the generic JDBC implementation. */
object PgJdbcDialect : JdbcDialect {
    override fun renderIdentifier(identifier: String): String =
        "\"${identifier.replace("\"", "\"\"")}\""

    override fun selectOne(table: String, whereClause: String?): String =
        "${select(table, whereClause)} LIMIT 1"

    override fun selectPage(table: String, orderBy: String, whereClause: String?): JdbcPageSql =
        JdbcPageSql(
            sql = "${select(table, whereClause)} ORDER BY ${quoteIdentifier(orderBy)} LIMIT ? OFFSET ?",
            parameterOrder = listOf(JdbcPageParameter.LIMIT, JdbcPageParameter.OFFSET)
        )

    override fun insertIfAbsent(table: String, columns: List<String>): String =
        "${insert(table, columns)} ON CONFLICT DO NOTHING"

    override fun upsertById(table: String, primaryKey: String, columns: List<String>): String {
        require(columns.isNotEmpty()) { "Upsert columns cannot be empty." }
        val allColumns = listOf(primaryKey) + columns
        return "${insert(table, allColumns)} ON CONFLICT (${quoteIdentifier(primaryKey)}) DO UPDATE SET " +
            columns.joinToString(", ") {
                val quoted = quoteIdentifier(it)
                "$quoted = EXCLUDED.$quoted"
            }
    }

    override fun update(table: String, columns: List<String>, whereClause: String?, limit: Int?): String {
        if (limit == null) return super.update(table, columns, whereClause, null)
        require(columns.isNotEmpty()) { "Update columns cannot be empty." }
        require(limit > 0) { "Update limit must be positive." }
        val quotedTable = quoteIdentifier(table)
        return buildString {
            append("UPDATE $quotedTable SET ")
            append(columns.joinToString(", ") { "${quoteIdentifier(it)} = ?" })
            append(" WHERE $quotedTable.ctid IN (SELECT $quotedTable.ctid FROM $quotedTable")
            whereClause?.let { append(" $it") }
            append(" LIMIT $limit)")
        }
    }

    override fun delete(table: String, whereClause: String?, limit: Int?): String {
        if (limit == null) return super.delete(table, whereClause, null)
        require(limit > 0) { "Delete limit must be positive." }
        val quotedTable = quoteIdentifier(table)
        return buildString {
            append("DELETE FROM $quotedTable WHERE $quotedTable.ctid IN (SELECT $quotedTable.ctid FROM $quotedTable")
            whereClause?.let { append(" $it") }
            append(" LIMIT $limit)")
        }
    }

    override fun autoIncrementClause(): String = " GENERATED BY DEFAULT AS IDENTITY"
}
