package io.github.heyhey123.skriptorm.impl.pg.database

import io.github.heyhey123.skriptorm.impl.jdbc.database.JdbcDialect

/**
 * PostgreSQL-specific SQL rendering; query execution remains in the generic JDBC implementation.
 *
 * `select one` and `select page` are not overridden. The dialect's defaults are `LIMIT 1` and
 * `ORDER BY … LIMIT ? OFFSET ?`, which is what PostgreSQL reads, so repeating them here would be two
 * copies of one statement waiting to drift apart — the earlier ones did exactly that and were identical.
 */
object PgJdbcDialect : JdbcDialect {

    override fun renderIdentifier(identifier: String): String =
        "\"${identifier.replace("\"", "\"\"")}\""

    override fun insertIfAbsent(table: String, columns: List<String>): String =
        "${insert(table, columns)} ON CONFLICT DO NOTHING"

    override fun upsertById(table: String, primaryKey: String, columns: List<String>): String {
        require(columns.isNotEmpty()) { "Upsert columns cannot be empty." }
        val allColumns = listOf(primaryKey) + columns
        return "${insert(table, allColumns)} ON CONFLICT (${quoteIdentifier(primaryKey)}) DO UPDATE SET " +
            columns.joinToString(", ") {
                val quoted = quoteIdentifier(it)
                "$quoted = EXCLUDED.$quoted"
            }
    }

    override fun update(table: String, columns: List<String>, whereClause: String?, limit: Int?): String {
        if (limit == null) return super.update(table, columns, whereClause, null)
        require(columns.isNotEmpty()) { "Update columns cannot be empty." }
        require(limit > 0) { "Update limit must be positive." }
        val quotedTable = quoteIdentifier(table)
        return buildString {
            append("UPDATE $quotedTable SET ")
            append(columns.joinToString(", ") { "${quoteIdentifier(it)} = ?" })
            append(" WHERE $quotedTable.ctid IN (SELECT $quotedTable.ctid FROM $quotedTable")
            whereClause?.let { append(" $it") }
            append(" LIMIT $limit)")
        }
    }

    override fun delete(table: String, whereClause: String?, limit: Int?): String {
        if (limit == null) return super.delete(table, whereClause, null)
        require(limit > 0) { "Delete limit must be positive." }
        val quotedTable = quoteIdentifier(table)
        return buildString {
            append("DELETE FROM $quotedTable WHERE $quotedTable.ctid IN (SELECT $quotedTable.ctid FROM $quotedTable")
            whereClause?.let { append(" $it") }
            append(" LIMIT $limit)")
        }
    }

    override fun autoIncrementClause(): String = " GENERATED BY DEFAULT AS IDENTITY"

    /**
     * The names this server's driver reports for the storages the PostgreSQL types write.
     *
     * `DatabaseMetaData` speaks PostgreSQL's internal names — `int2` for a `SMALLINT`, `int4` for the `INT`
     * this module declares, `int8` for a `BIGINT`, `float4` and `float8` for a `REAL` and a
     * `DOUBLE PRECISION`, `bool`, and `bytea` for everything binary — while `information_schema` shows the
     * standard ones, which is why `PgSchemaIntegrationTest` reads the second and records the first. The
     * values are where the declaration side of the comparison lands: the shared table maps `INT` to
     * `INTEGER`, so `int4` has to arrive there too, and a `float4` has to be the `REAL` this module writes
     * rather than the `FLOAT` the generic dialect would call it. `float8` arrives on `DOUBLE` for the same
     * reason: a name is answered by one table and no second lookup follows, so a value has to be a name the
     * declaration side already stands on — a `double precision` declaration lands on `DOUBLE` now that the
     * shared table reads the standard spelling of it.
     *
     * `bit` is deliberately absent. It is what the MySQL family calls the one-byte boolean it stores, and
     * PostgreSQL's `bit(1)` is a bit string: reading one as a `boolean` is not what a declaration of
     * `boolean` asks for, and it was only ever accepted because the shared table could not tell the two
     * servers apart. `BYTEA` is here for the same reason it is not shared — no other server has the name.
     */
    override val typeAliases: Map<String, String> = mapOf(
        "INT2" to "SMALLINT",
        "INT4" to "INTEGER",
        "INT8" to "BIGINT",
        "FLOAT4" to "REAL",
        "FLOAT8" to "DOUBLE",
        "BOOL" to "BOOLEAN",
        "BYTEA" to "BLOB"
    )
}
