package io.github.heyhey123.skriptorm.impl.pg.database

import io.github.heyhey123.skriptorm.impl.jdbc.database.JdbcDialect

/**
 * PostgreSQL-specific SQL rendering; query execution remains in the generic JDBC implementation.
 *
 * The default `LIMIT` queries already work in PostgreSQL, so this dialect inherits them.
 */
object PgJdbcDialect : JdbcDialect {

    override fun renderIdentifier(identifier: String): String =
        "\"${identifier.replace("\"", "\"\"")}\""

    override fun insertIfAbsent(table: String, columns: List<String>): String =
        "${insert(table, columns)} ON CONFLICT DO NOTHING"

    override fun upsertById(table: String, primaryKey: String, columns: List<String>): String {
        require(columns.isNotEmpty()) { "Upsert columns cannot be empty." }
        val allColumns = listOf(primaryKey) + columns
        return "${insert(table, allColumns)} ON CONFLICT (${quoteIdentifier(primaryKey)}) DO UPDATE SET " +
            columns.joinToString(", ") {
                val quoted = quoteIdentifier(it)
                "$quoted = EXCLUDED.$quoted"
            }
    }

    override fun update(table: String, columns: List<String>, whereClause: String?, limit: Int?): String {
        if (limit == null) return super.update(table, columns, whereClause, null)
        require(columns.isNotEmpty()) { "Update columns cannot be empty." }
        require(limit > 0) { "Update limit must be positive." }
        val quotedTable = quoteIdentifier(table)
        return buildString {
            append("UPDATE $quotedTable SET ")
            append(columns.joinToString(", ") { "${quoteIdentifier(it)} = ?" })
            append(" WHERE $quotedTable.ctid IN (SELECT $quotedTable.ctid FROM $quotedTable")
            whereClause?.let { append(" $it") }
            append(" LIMIT $limit)")
        }
    }

    override fun delete(table: String, whereClause: String?, limit: Int?): String {
        if (limit == null) return super.delete(table, whereClause, null)
        require(limit > 0) { "Delete limit must be positive." }
        val quotedTable = quoteIdentifier(table)
        return buildString {
            append("DELETE FROM $quotedTable WHERE $quotedTable.ctid IN (SELECT $quotedTable.ctid FROM $quotedTable")
            whereClause?.let { append(" $it") }
            append(" LIMIT $limit)")
        }
    }

    override fun autoIncrementClause(): String = " GENERATED BY DEFAULT AS IDENTITY"

    /**
     * Maps PostgreSQL's internal type names from `DatabaseMetaData` to the names used by schema
     * verification. For example, the driver reports `int4` for a column declared `INT`, which the
     * shared aliases normalize to `INTEGER`. PostgreSQL's `float4` maps to `REAL`, not the generic
     * dialect's `FLOAT`.
     *
     * PostgreSQL's `bit(1)` is a bit string, so it must not be accepted as a `boolean` column.
     * `BYTEA` is specific to PostgreSQL and therefore belongs in this dialect.
     */
    override val typeAliases: Map<String, String> = mapOf(
        "INT2" to "SMALLINT",
        "INT4" to "INTEGER",
        "INT8" to "BIGINT",
        "FLOAT4" to "REAL",
        "FLOAT8" to "DOUBLE",
        "BOOL" to "BOOLEAN",
        "BYTEA" to "BLOB"
    )
}
