package io.github.heyhey123.skriptorm.impl.mongo.integration

import io.github.heyhey123.skriptorm.condition.Condition
import io.github.heyhey123.skriptorm.condition.WhereClause
import io.github.heyhey123.skriptorm.table.Column
import io.github.heyhey123.skriptorm.table.Table
import kotlinx.coroutines.runBlocking
import org.junit.jupiter.api.Test
import java.util.UUID
import kotlin.test.assertEquals
import kotlin.test.assertNotEquals
import kotlin.test.assertNull
import kotlin.test.assertTrue

/**
 * The statements of the MongoDB implementation against a real server.
 *
 * What is checked here is the behaviour a script depends on and a unit test cannot reach: that a value
 * survives the round trip through the converter it was declared with, that a filter finds the row it
 * describes, that a limit limits, and that the count a write reports says what happened. Every read goes
 * through the implementation's own cursor, so a cursor that walks one row too many fails this suite.
 */
class MongoCrudIntegrationTest : MongoIntegrationTestBase() {

    @Test
    fun `an inserted row is what select by id finds`() = runBlocking<Unit> {
        recreateTable()
        queries.insertOne(userValues(name = "first", age = 30)).execute(usersTable)

        val stored = allUsers().single()
        val found = queries.selectById(stored.id).execute(usersTable).readUsers()

        assertEquals(listOf(stored), found)
    }

    @Test
    fun `a key the statement leaves out is generated by the table`() = runBlocking<Unit> {
        recreateTable()
        queries.insertOne(userValues(name = "first")).execute(usersTable)
        queries.insertOne(userValues(name = "second")).execute(usersTable)

        val ids = allUsers().map { it.id }

        assertEquals(2, ids.size)
        assertNotEquals(ids[0], ids[1], "a counter, not a constant, fills the key")
        assertTrue(ids.all { it > 0 }, "the counter starts above zero, so the key is never absent: $ids")
    }

    @Test
    fun `a key is never handed out twice, however many rows are removed`() = runBlocking<Unit> {
        recreateTable()
        queries.insertOne(userValues(name = "first")).execute(usersTable)
        queries.insertOne(userValues(name = "second")).execute(usersTable)
        val highest = allUsers().maxOf { it.id }

        // The row holding the highest key goes first, then every other row. A counter that read the rows
        // instead of counting them would hand that key out again, and the unique index would refuse the
        // insert: deleting rows must leave the sequence where it was.
        queries.delete(1, matching("id", highest)).execute(usersTable)
        queries.delete(null, null).execute(usersTable)
        assertEquals(0L, rawCount())

        queries.insertOne(userValues(name = "third")).execute(usersTable)

        assertTrue(
            allUsers().single().id > highest,
            "the next key is past the highest one ever handed out, not the highest one still stored"
        )
    }

    @Test
    fun `a key written explicitly is never handed out again`() = runBlocking<Unit> {
        recreateTable()
        queries.insertOne(userValues(name = "first", id = 100)).execute(usersTable)

        queries.insertOne(userValues(name = "second")).execute(usersTable)

        assertTrue(
            allUsers().single { it.name == "second" }.id > 100,
            "the counter was raised to the key the first statement brought, so it cannot issue it again"
        )
    }

    @Test
    fun `a key an upsert brought is never handed out again`() = runBlocking<Unit> {
        recreateTable()
        queries.upsertById(50, mapOf("name" to "first")).execute(usersTable)

        queries.insertOne(userValues(name = "second")).execute(usersTable)

        assertTrue(
            allUsers().single { it.name == "second" }.id > 50,
            "an upsert can create the row its key names, so it raises the counter like an insert does"
        )
    }

    @Test
    fun `every stored type comes back unchanged`() = runBlocking<Unit> {
        recreateTable()
        val uid = UUID.randomUUID()
        queries.insertOne(userValues(name = "first", age = 30, score = 1.5, uid = uid)).execute(usersTable)

        val stored = allUsers().single()

        assertEquals("first", stored.name)
        assertEquals(30, stored.age)
        assertEquals(1.5, stored.score)
        assertEquals(uid, stored.uid)
    }

    @Test
    fun `a column a row did not carry reads as null`() = runBlocking<Unit> {
        recreateTable()
        queries.insertOne(userValues(name = "first")).execute(usersTable)

        val stored = allUsers().single()

        assertNull(stored.age)
        assertNull(stored.score)
        assertNull(stored.uid)
    }

    @Test
    fun `select by id finds nothing for an identifier no row holds`() = runBlocking<Unit> {
        recreateTable()
        queries.insertOne(userValues(name = "first", id = 1)).execute(usersTable)

        assertTrue(queries.selectById(404).execute(usersTable).readUsers().isEmpty())
    }

    @Test
    fun `select one stops at the first match, and finds nothing when there is none`() = runBlocking<Unit> {
        recreateTable()
        queries.insertOne(userValues(name = "first", id = 1, age = 30)).execute(usersTable)
        queries.insertOne(userValues(name = "second", id = 2, age = 30)).execute(usersTable)

        assertEquals(1, queries.selectOne(matching("age", 30)).execute(usersTable).readUsers().size)
        assertTrue(queries.selectOne(matching("age", 99)).execute(usersTable).readUsers().isEmpty())
    }

    @Test
    fun `a where clause joins its conditions and can negate them`() = runBlocking<Unit> {
        recreateTable()
        queries.insertOne(userValues(name = "first", id = 1, age = 30)).execute(usersTable)
        queries.insertOne(userValues(name = "second", id = 2, age = 40)).execute(usersTable)
        queries.insertOne(userValues(name = "third", id = 3, age = 50)).execute(usersTable)

        val all = queries.selectMany(
            WhereClause.All(false, listOf(condition("age", 30), condition("name", "first")))
        ).execute(usersTable).readUsers()
        val any = queries.selectMany(
            WhereClause.Any(false, listOf(condition("age", 30), condition("age", 50)))
        ).execute(usersTable).readUsers()
        // A negated clause is the one filter MongoDB cannot express with `$not`, which belongs to a field
        // and is refused at the top level: this is what says the whole filter is negated instead.
        val none = queries.selectMany(
            WhereClause.Any(true, listOf(condition("age", 30), condition("age", 50)))
        ).execute(usersTable).readUsers()

        assertEquals(listOf("first"), all.map { it.name })
        assertEquals(setOf("first", "third"), any.map { it.name }.toSet())
        assertEquals(listOf("second"), none.map { it.name })
    }

    @Test
    fun `select page walks the pages in key order`() = runBlocking<Unit> {
        recreateTable()
        (10..14).forEach { queries.insertOne(userValues(name = "row$it", id = it)).execute(usersTable) }

        assertEquals(listOf(10, 11), queries.selectPage(2, 1, null).execute(usersTable).readUsers().map { it.id })
        assertEquals(listOf(12, 13), queries.selectPage(2, 2, null).execute(usersTable).readUsers().map { it.id })
        assertEquals(listOf(14), queries.selectPage(2, 3, null).execute(usersTable).readUsers().map { it.id })
    }

    @Test
    fun `select page refuses a table without a primary key`() = runBlocking<Unit> {
        val keyless = Table("orm_keyless", listOf(Column("name", stringType)))
        collectionOf(keyless.name).drop()
        database.registerTable(keyless)

        val error = failing { queries.selectPage(2, 1, null).execute(keyless) }

        assertEquals("Stable pagination requires table orm_keyless to define a primary key.", error.message)
    }

    @Test
    fun `an update counts the rows the filter matched, not the rows it changed`() = runBlocking<Unit> {
        recreateTable()
        queries.insertOne(userValues(name = "first", id = 1)).execute(usersTable)

        val unchanged = queries.update(mapOf("name" to "first"), 1, matching("id", 1)).execute(usersTable)
        val changed = queries.update(mapOf("name" to "second"), 1, matching("id", 1)).execute(usersTable)

        assertEquals(1L, unchanged.affectedCount, "a row written with the value it holds is still a row that matched")
        assertEquals(1L, changed.affectedCount)
        assertEquals("second", allUsers().single().name)
    }

    @Test
    fun `a limited update changes only as many rows as it is given`() = runBlocking<Unit> {
        recreateTable()
        (1..4).forEach { queries.insertOne(userValues(name = "row$it", id = it)).execute(usersTable) }

        val result = queries.update(mapOf("name" to "changed"), 2, null).execute(usersTable)

        assertEquals(2L, result.affectedCount)
        assertEquals(2, allUsers().count { it.name == "changed" })
    }

    @Test
    fun `a limited delete removes only as many rows as it is given`() = runBlocking<Unit> {
        recreateTable()
        (1..4).forEach { queries.insertOne(userValues(name = "row$it", id = it)).execute(usersTable) }

        val result = queries.delete(2, null).execute(usersTable)

        assertEquals(2L, result.affectedCount)
        assertEquals(2, allUsers().size)
        assertEquals(2L, rawCount(), "the rows a limit leaves behind are still there")
    }

    @Test
    fun `insert if absent keeps the row a key already holds`() = runBlocking<Unit> {
        recreateTable()
        assertEquals(1L, queries.insertOne(userValues(name = "first", id = 1)).execute(usersTable).affectedCount)

        val again = queries.insertIfAbsent(userValues(name = "second", id = 1)).execute(usersTable)
        val fresh = queries.insertIfAbsent(userValues(name = "third", id = 2)).execute(usersTable)

        assertEquals(0L, again.affectedCount, "a key the table already holds is not written a second time")
        assertEquals(1L, fresh.affectedCount)
        assertEquals(listOf("first", "third"), allUsers().sortedBy { it.id }.map { it.name })
    }

    @Test
    fun `upsert by id inserts a row and then writes it`() = runBlocking<Unit> {
        recreateTable()

        val inserted = queries.upsertById(1, mapOf("name" to "first")).execute(usersTable)
        val updated = queries.upsertById(1, mapOf("name" to "second")).execute(usersTable)

        assertEquals(1L, inserted.affectedCount)
        assertEquals(1L, updated.affectedCount)
        assertEquals("second", allUsers().single().name)
    }

    @Test
    fun `delete by id removes that row and nothing else`() = runBlocking<Unit> {
        recreateTable()
        queries.insertOne(userValues(name = "first", id = 1)).execute(usersTable)
        queries.insertOne(userValues(name = "second", id = 2)).execute(usersTable)

        val result = queries.deleteById(1).execute(usersTable)

        assertEquals(1L, result.affectedCount)
        assertEquals(listOf("second"), allUsers().map { it.name })
    }

    @Test
    fun `a write that matches nothing reports zero`() = runBlocking<Unit> {
        recreateTable()

        assertEquals(0L, queries.update(mapOf("name" to "changed"), null, matching("id", 1)).execute(usersTable).affectedCount)
        assertEquals(0L, queries.updateById(1, mapOf("name" to "changed")).execute(usersTable).affectedCount)
        assertEquals(0L, queries.delete(null, matching("id", 1)).execute(usersTable).affectedCount)
        assertEquals(0L, queries.deleteById(1).execute(usersTable).affectedCount)
    }

    private fun condition(column: String, value: Any?): Condition = Condition.Equals(column, value)

    private fun matching(column: String, value: Any?): WhereClause =
        WhereClause.All(false, listOf(condition(column, value)))
}
