package io.github.heyhey123.skriptorm.impl.pg.database

import io.github.heyhey123.skriptorm.impl.jdbc.database.JdbcPageParameter
import io.github.heyhey123.skriptorm.impl.jdbc.type.IntJdbcDataType
import io.github.heyhey123.skriptorm.impl.jdbc.type.StringJdbcDataType
import io.github.heyhey123.skriptorm.table.Column
import io.github.heyhey123.skriptorm.table.Table
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertTrue

/**
 * Pins the SQL this dialect renders. The integration tests say whether PostgreSQL accepts it; these say
 * what was rendered, so a change here is visible without a server.
 */
class PgJdbcDialectTest {

    @Test
    fun `identifier quoting follows the standard and escapes an inner quote`() {
        assertEquals("\"users\"", PgJdbcDialect.quoteIdentifier("users"))
        assertEquals("\"用户_名\"", PgJdbcDialect.quoteIdentifier("用户_名"))

        // A quote cannot reach the quoting step as a plain name: the shared validation refuses it
        // first, and the escaping behind that only matters for a name that gets past it.
        assertFailsWith<IllegalArgumentException> { PgJdbcDialect.quoteIdentifier("user\"name") }
        assertEquals("\"user\"\"name\"", PgJdbcDialect.renderIdentifier("user\"name"))
        assertFailsWith<IllegalArgumentException> { PgJdbcDialect.quoteIdentifier("has space") }
    }

    @Test
    fun `selects page with limit and offset in that order`() {
        assertEquals("SELECT * FROM \"users\"", PgJdbcDialect.select("users"))
        assertEquals(
            "SELECT * FROM \"users\" WHERE \"age\" >= ? LIMIT 1",
            PgJdbcDialect.selectOne("users", "WHERE \"age\" >= ?")
        )

        val page = PgJdbcDialect.selectPage("users", "id", "WHERE \"age\" >= ?")
        assertEquals("SELECT * FROM \"users\" WHERE \"age\" >= ? ORDER BY \"id\" LIMIT ? OFFSET ?", page.sql)
        assertEquals(listOf(JdbcPageParameter.LIMIT, JdbcPageParameter.OFFSET), page.parameterOrder)
    }

    @Test
    fun `writes use on conflict and an identity column`() {
        assertEquals("INSERT INTO \"users\" (\"id\") VALUES (?)", PgJdbcDialect.insert("users", listOf("id")))
        assertEquals(
            "INSERT INTO \"users\" (\"id\") VALUES (?) ON CONFLICT DO NOTHING",
            PgJdbcDialect.insertIfAbsent("users", listOf("id"))
        )
        assertEquals(
            "INSERT INTO \"users\" (\"id\", \"name\") VALUES (?, ?) " +
                "ON CONFLICT (\"id\") DO UPDATE SET \"name\" = EXCLUDED.\"name\"",
            PgJdbcDialect.upsertById("users", "id", listOf("name"))
        )
        assertEquals(" GENERATED BY DEFAULT AS IDENTITY", PgJdbcDialect.autoIncrementClause())
    }

    @Test
    fun `an unlimited write is written as it is and a limited one goes through ctid`() {
        assertEquals(
            "UPDATE \"users\" SET \"name\" = ? WHERE \"id\" = ?",
            PgJdbcDialect.update("users", listOf("name"), "WHERE \"id\" = ?", null)
        )
        assertEquals(
            "UPDATE \"users\" SET \"name\" = ? WHERE \"users\".ctid IN " +
                "(SELECT \"users\".ctid FROM \"users\" WHERE \"age\" >= ? LIMIT 2)",
            PgJdbcDialect.update("users", listOf("name"), "WHERE \"age\" >= ?", 2)
        )
        assertEquals("DELETE FROM \"users\"", PgJdbcDialect.delete("users", null, null))
        assertEquals(
            "DELETE FROM \"users\" WHERE \"users\".ctid IN (SELECT \"users\".ctid FROM \"users\" LIMIT 3)",
            PgJdbcDialect.delete("users", null, 3)
        )
    }

    @Test
    fun `ddl applies sizes nullability keys and identity`() {
        val table = Table(
            "users",
            listOf(
                Column("id", IntJdbcDataType(), isPrimaryKey = true, isAutoIncrement = true),
                Column("name", StringJdbcDataType(), size = 40, isNullable = true)
            )
        )

        assertEquals(
            "CREATE TABLE IF NOT EXISTS \"users\" " +
                "(\"id\" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, \"name\" VARCHAR(40))",
            PgJdbcDialect.createTable(table)
        )
    }

    @Test
    fun `invalid columns limits and declarations are refused`() {
        assertFailsWith<IllegalArgumentException> { PgJdbcDialect.insert("users", emptyList()) }
        assertFailsWith<IllegalArgumentException> { PgJdbcDialect.insertIfAbsent("users", emptyList()) }
        assertFailsWith<IllegalArgumentException> { PgJdbcDialect.upsertById("users", "id", emptyList()) }
        assertFailsWith<IllegalArgumentException> { PgJdbcDialect.update("users", listOf("id"), null, 0) }
        assertFailsWith<IllegalArgumentException> { PgJdbcDialect.delete("users", null, -1) }
        assertFailsWith<IllegalArgumentException> {
            PgJdbcDialect.renderColumn("name", StringJdbcDataType(), null, false, true, true)
        }
    }

    /**
     * The names the driver reports for this module's storages, which `PgSchemaIntegrationTest` reads off a
     * real server through `information_schema` and the driver's own metadata. The values are where the
     * declaration side lands: a `float4` is the `REAL` this module writes, not the `FLOAT` the generic
     * dialect calls it, so the two spellings meet. A name is answered once and not looked up again, so
     * `float8` has to arrive where a `double precision` declaration lands — `DOUBLE` — rather than on the
     * standard spelling the shared table would read further; the server job of the CI run that added this
     * line is what caught it arriving on the spelling instead.
     */
    @Test
    fun `the type names the driver reports are this dialect's own`() {
        assertEquals("SMALLINT", PgJdbcDialect.typeAliases.getValue("INT2"))
        assertEquals("INTEGER", PgJdbcDialect.typeAliases.getValue("INT4"))
        assertEquals("BIGINT", PgJdbcDialect.typeAliases.getValue("INT8"))
        assertEquals("REAL", PgJdbcDialect.typeAliases.getValue("FLOAT4"))
        assertEquals("DOUBLE", PgJdbcDialect.typeAliases.getValue("FLOAT8"))
        assertEquals("BOOLEAN", PgJdbcDialect.typeAliases.getValue("BOOL"))
        assertEquals("BLOB", PgJdbcDialect.typeAliases.getValue("BYTEA"))

        // `bit(1)` is a bit string here and the one-byte boolean to the MySQL family. Reading one as the
        // other is what a declaration of `boolean` does not ask for.
        assertTrue("BIT" !in PgJdbcDialect.typeAliases, "PostgreSQL's bit is not its boolean")
    }
}
